### PR TITLE
Closes #36 - fixes page scroll position & hash in url on page load

### LINKED ISSUE #36: Issue with scroll position on page load
Page position is not accurate at certain breakpoints when page is loaded

### PR DESCRIPTION
**Pull request by nicholashamilton**

### CODE REVIEW

File: src/core/runtime.ts [hunk 1]
```diff
@@ -160,6 +161,20 @@ class Runtime {
         }
     }
 
+    private handlePageScrollPosition(): void {
+        if (window.location.hash) {
+            /** Scroll to hash element */
+            const element = document.body.querySelector(window.location.hash);
+            if (element) {
+                const elementYPosition = (element.getBoundingClientRect().top - document.body.getBoundingClientRect().top) as number;
```
Comment (codewithkyle) [inline src/core/runtime.ts]: Was there any particular reason we're calculating the offset on the element instead using the `scrollIntoView()` method?

Ref: [Element API](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView).

**Review by codewithkyle — CHANGES_REQUESTED** [review]

File: src/core/runtime.ts [hunk 2]
```diff
@@ -160,6 +161,19 @@ class Runtime {
         }
     }
 
+    private handlePageScrollPosition(): void {
+        if (window.location.hash) {
```
Comment (bamccaul-dev) [inline src/core/runtime.ts:165]: Will this take into account any statically set nav bars or other elements?

**Review by codewithkyle — APPROVED** [review]

**Review by bamccaul-dev — CHANGES_REQUESTED** [review]

File: src/core/runtime.ts (hunk 2 above)
Comment (codewithkyle) [reply src/core/runtime.ts:165]: We'll address this in #42

**Review by bamccaul-dev — APPROVED** [review]
